### ISSUE TITLE
Верстка портится при заужении окна

### ISSUE THREAD

**Issue by alexanderpono** [ermakof/lines#11]
Firefox 88.0, Linux Mint 18.3 64bit 
https://ermakof.github.io/lines/#/auth
1) Входим в игру
2) Уменьшаем ширину окна до максимума.

**Ожидаемая реакция:** с некоторого момента контент страницы перестает сужаться, появляется горизонтальный скроллер. При этом - верстка UI игры сохраняет целостность.

**Фактическая реакция:** верстка UI игры портится - см. скриншот:
[скриншот](https://pastenow.ru/G4Y5K)

**Comment by ermakof** [comment]
Исправлено.
